<?php include('navbar.php');?>
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>llb</title>
</head>
<body>
	<h1>Bachelor of Laws</h1><br>
	"LLB" redirects here. For other uses, see LLB (disambiguation).
Bachelor of Laws (Latin: Legum Baccalaureus; LL.B.) is an undergraduate law degree in the United Kingdom and most common law jurisdictions.[1] Bachelor of Laws is also the name of the law degree awarded by universities in the People's Republic of China, Hong Kong S.A.R., Macau S.A.R., India, Pakistan, Kenya, Ghana, Nigeria, South Africa, Botswana, Israel, Brazil, Tanzania, Zambia, and many other jurisdictions. The Bachelor of Laws was also the primary law degree in the United States, but was phased out in favour of the Juris Doctor degree in the 1960s.[2]<br>
The first academic degrees were all law degrees in medieval universities, and the first law degrees were doctorates.[3][4][5] The foundations of the first universities were the glossators of the 11th century, which were also schools of law.[6] The first university, that of Bologna, was founded as a school of law by four famous legal scholars in the 12th century who were students of the glossator school in that city. The University of Bologna served as the model for other law schools of the medieval age.[7] While it was common for students of law to visit and study at schools in other countries, such was not the case with England because of the English rejection of Roman law (except for certain jurisdictions such as the Admiralty Court) and, although the University of Oxford and the University of Cambridge did teach canon law until the English Reformation, its importance was always superior to civil law in those institutions.[8]

Origin of the LL.B.
"LL.B." stands for Legum Baccalaureus in Latin. The "LL." of the abbreviation for the degree is from the genitive plural legum ("of laws"). Creating an abbreviation for a plural, especially from Latin, is often done by doubling the first letter (e.g., "pp." for "pages"). It is sometimes erroneously called "Bachelor of Legal Letters" to account for the double "L".

The bachelor's degree originated at the University of Paris, whose system was implemented at Oxford and Cambridge.[9] The "arts" designation of the degree traditionally signifies that the student has undertaken a certain amount of study of the classics.[10] In continental Europe the bachelor's degree was phased out in the 18th or early 19th century but it continued at Oxford and Cambridge.

The teaching of law at Oxford University was for philosophical or scholarly purposes and not meant to prepare one to practise law.[11] Professional training for practising common law in England was undertaken at the Inns of Court, but over time the training functions of the Inns lessened considerably and apprenticeships with individual practitioners arose as the prominent medium of preparation.[12] However, because of the lack of standardization of study and of objective standards for appraisal of these apprenticeships, the role of universities became subsequently of importance for the education of lawyers in the English speaking world.[13]

In England in 1292 when Edward I first requested that lawyers be trained, students merely sat in the courts and observed, but over time the students would hire professionals to lecture them in their residences, which led to the institution of the Inns of Court system.[14] The original method of education at the Inns of Court was a mix of moot court-like practice and lecture, as well as court proceedings observation.[15] By the seventeenth century, the Inns obtained a status as a kind of university akin to the University of Oxford and the University of Cambridge, though very specialized in purpose.[16] With the frequent absence of parties to suits during the Crusades, the importance of the lawyer role grew tremendously, and the demand for lawyers grew.[17]

Traditionally Oxford and Cambridge did not see common law as worthy of study, and included coursework in law only in the context of canon and civil law and for the purpose of the study of philosophy or history only. The apprenticeship programme for solicitors thus emerged, structured and governed by the same rules as the apprenticeship programmes for the trades.[18] The training of solicitors by apprenticeship was formally established by an act of parliament in 1729. William Blackstone became the first lecturer in English common law at the University of Oxford in 1753, but the university did not establish the programme for the purpose of professional study, and the lectures were very philosophical and theoretical in nature.[19] Blackstone insisted that the study of law should be university based, where concentration on foundational principles can be had, instead of concentration on detail and procedure had through apprenticeship and the Inns of Court.[20]

The Inns of Court continued but became less effective, and admission to the bar still did not require any significant educational activity or examination. Therefore in 1846 the Parliament examined the education and training of prospective barristers and found the system to be inferior to the legal education provided in the United States. Therefore, formal schools of law were called for, but not finally established until later in the century, and even then the bar did not consider a university degree in admission decisions.[13] When law degrees were required by the English bar and bar associations in other common law countries, the LL.B. became the uniform degree for lawyers in common law countries.

<h2>Structure of LL.B. programmes</h2>
Historically, law students studied both canon law and civil law. Today, this is much less common among common law countries, who now study the English-derived common law system, which includes the criminal law of most jurisdictions. However, a few institutions continue to offer alternatives to strictly English common law: for example Cardiff University's Department of Canon (Ecclesiastical) Law, or combined programmes in common and French civil law (pertinent to Canada's pluralist legal system) at McGill University and University of Ottawa.

<h2>Common law jurisdictions in general</h2>
In most common law countries (with the exceptions of all Canadian provinces except Quebec, and the U.S.), the Bachelor of Laws programme is generally entered directly after completion of secondary school. In England and Wales it is also possible to study a programme for conversion to the legal profession following completion of a previous undergraduate degree unrelated to law (the Graduate Diploma in Law), which entitles graduates to take the vocational courses for entry into the legal profession. Master's degree courses are also offered to university graduates; those who graduate from such courses are entitled to use the initials LL.M. (Master of Laws).

<h2>Australia</h2>
A qualifying law degree for the purposes of admission as a lawyer in Australia is either the undergraduate LL.B. (Bachelor of Laws) programmes at accredited universities recognised by the admission board of the respective state, or the graduate J.D. (Juris Doctor). Every recognised qualification of each admission board is reciprocally recognised. However, prior to degrees, there existed an alternative to a degree to become a lawyer in Australia, which was either the Barrister's Admission Board, or the Solicitor's Admission Board, whose examinations rendered one eligible to be admitted respectively, the successor of these boards that still operates this alternative is the Legal Profession Admission Board which issues the distinct Diploma in Law which is equivalent to either an LL.B. or a J.D. Law degrees typically last 4 years for undergraduate admission or 3 years for university graduates.

Additionally, of the thirty-eight law schools, thirteen of those universities have also started offering the Juris Doctor (J.D.) as a graduate-entry degree.

<h2>Bangladesh</h2>
In Bangladesh, as in other common-law countries, obtaining a Bachelor of Laws (LL.B.) degree is a prerequisite for practising as an advocate in a court of law. Both LL.B. and LL.B. (Hons.) degrees are offered at public and private universities. Only seven public universities offer LL.B. (Hons.) degree. These universities also offer one-year LL.M. courses. Some private universities also offer four-year LL.B. (Hons.) degrees and one-year LL.M. courses. The National University of Bangladesh also offers a two-year LL.B. degree to graduates of subjects other than law. But remarkably, the department of Law, University of Rajshahi is the first institute in South Asia to offer bachelors degree in law with honors as B. Jur.(Bachelor of Jurisprudence) and M. Jur. (Masters of Jurisprudence) from 1970 (not offered in the years 1971 & 1972). [21] Later on they were replaced with LL. B (Hons.) and LL. M degree respectively. This institute is considered the leading institute to study legal science in Bangladesh having a great number of alumni and former members of the faculty around the world including former president, chief justice, ministers of several governments and many of the former and current judges of the apex courts and the courts of the lower judiciary of Bangladesh and many more formidable legal minds of the country. As per the number of participants in the admission tests, this is considered one of the most desirable choices for the High school/college students of Bangladesh.

</body>
</html>